### Get all diaries
GET http://localhost:3000/api/diaries

### Get a diary by id
GET http://localhost:3000/api/diaries/5

### Create a diary
POST http://localhost:3000/api/diaries
Content-Type: application/json

{
  "date": "2025-01-01",
  "weather": "a",
  "visibility": "poor",
  "comment": "test"
}