GET http://localhost:3001/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyMiIsImlkIjoiNjgzMDgyOTU1NzJjN2ZjZDdjODE2NmM2IiwiaWF0IjoxNzQ4MDA5NjU0LCJleHAiOjE3NDgwMTMyNTR9.AqsL4LlAu8yng82kc4MQhmSRXDiE17-CcatSXK97-O0

###
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyMiIsImlkIjoiNjgzMDgyOTU1NzJjN2ZjZDdjODE2NmM2IiwiaWF0IjoxNzQ4MDA5ODEwLCJleHAiOjE3NDgwMTM0MTB9.JfvdK4Ush_4-ChPvKKkJz5ECVBHitFqPLZkWNyksT-4

{
    "title": "Test Blog",
    "author": "Test Author", 
    "url": "https://test.com",
    "likes": 10,
    "userId": "68308295572c7fcd7c8166c6"
}

###
DELETE http://localhost:3001/api/blogs/68306c9fe518cc9a30153ec1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3R1c2VyMiIsImlkIjoiNjgzMDgyOTU1NzJjN2ZjZDdjODE2NmM2IiwiaWF0IjoxNzQ4MDA5NjU0LCJleHAiOjE3NDgwMTMyNTR9.AqsL4LlAu8yng82kc4MQhmSRXDiE17-CcatSXK97-O0


