GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blog
s
Content-Type: application/json

{
    "title": "Test Blog",
    "author": "Test Author",
    "url": "https://test.com",
    "likes": 10
}
