### Get all patients
GET http://localhost:3001/api/patients

### Get a patient by id
GET http://localhost:3001/api/patients/d2773336-f723-11e9-8f0b-362b9e155667


### Create a patient
POST http://localhost:3001/api/patients
Content-Type: application/json

{
  "name": "John Doe",
  "dateOfBirth": "asdsa",
  "ssn": "1234567890",
  "gender": "male",
  "occupation": "Software Engineer"
}